language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-22
  - android-28
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-22
script:
- ./gradlew build
before_install:
- openssl aes-256-cbc -K $encrypted_6de5e2e53dd7_key -iv $encrypted_6de5e2e53dd7_iv
  -in app/gradle.properties.enc -out app/gradle.properties -d
